version: '3'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_DATABASE: boro
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

  redis-server:
    image: redis:latest
    container_name: redis_server
    restart: always
    volumes:
      - redis_data:/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: mysql-server
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      REDIS_URL: redis-server
    ports:
      - 8080:8080
    depends_on:
      - mysql-server
      - redis-server

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
